{% set name = "bython" %}
{% set version = "0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bython-{{ version }}.tar.gz
  sha256: 49c73aa53f17e0180f6789cc434227f24ea5c1590cc67ce0ac8d799f506f3972

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    # bython contains unix-style scripts that are not supported on Windows
    - __unix

test:
  imports:
    - bython
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - bython --version
    - by2py --version
    - py2by --version

about:
  home: https://github.com/mathialo/bython
  summary: Python with braces
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
